name: Test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  unit-test:
    name: Unit Test
    runs-on: [self-hosted, arm64, cpu=2, memory=4Gi]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        id: go
        with:
          go-version: 1.20

      - name: Check out code
        uses: actions/checkout@v2

      - name: Cache modules
        id: cache-go-modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Install dependencies
        run: make deps

      - name: Run Unit Test
        run: make test

      - name: Run lint
        run: make lint

      - name: Run go vet
        run: make vet

      - name: Run gosec
        run: make sec
