name: Test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  unit-test:
    name: Unit Test
    runs-on: self-hosted-2Gi-arm64
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        id: go
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v2

      - name: Cache modules
        id: cache-go-modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Get dependencies
        run: go mod download

      - name: Run Unit Test
        run: go test -v ./...

      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --enable=lll --out-${NO_FUTURE}format colored-line-number

      - name: Run go vet
        run: go vet ./...

      - name: Run gosec
        uses: securego/gosec@master
        with:
          args: ./...
